name: Tag
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
  id-token: write
  packages: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "[Setup] repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "[CD] GoReleaser"
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
