name: UART-CL Linux Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Execute unit tests
      working-directory: "UART-CL By TheCod3r"
      run: dotnet test

    - name: Build release
      working-directory: "UART-CL By TheCod3r"
      run: dotnet publish

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "UART-CL Linux"
        path: "UART-CL By TheCod3r/bin/Release/net6.0/linux-x64/publish/"